..\exe\rusconv ' orosz\orosz.cdw orosz.cdw
..\exe\rusconv " orosz\mnutx_o3.asm mnutx_o3.asm
..\exe\rusconv " orosz\errorso.asm errorso.asm
..\exe\rusconv " orosz\althelpo.asm althelpo.asm
..\exe\rusconv " orosz\ctrhelpo.asm ctrhelpo.asm
..\exe\rusconv ' orosz\orosznyo.pas orosznyo.pas
..\exe\helpconv orosz\ekszero.hlp ekszero.hlp
..\exe\althconv orosz\ekshlpo1.doc ekshlpo1.doc
tasm mnutx_o3
tasm errorso
tasm althelpo
tasm ctrhelpo